### ISSUE TITLE
Email Templates Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/captcha-master#12]
Hi Shifi,

Here are the tasks for you for Email Templates Page/Screen.

• Six options should be list out in "Choose Email Template" drop down list. Please check the below options :
        1. Template For User Success
        2. Template For User Failure
        3. Template For IP Address Blocked
        4. Template For IP Address Unblocked
        5. Template For IP Range Blocked
        6. Template For IP Range Unblocked
• CC, Bcc, Subject and Message all fields are mandatory. 
• Special char Validation should be checked on Subject and Message fields.
• Email validation should be checked on CC and Bcc fields.
•       CC,Bcc and Subject will contain the value from meta table according to selected value of "Choose Email Template" field. 
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and   needed.

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy5** [comment]
# Change Files:
1. lib/install-script.php
2. lib/action-library.php
3. lib/helper.php
4. includes/footer.php
5. views/email-templates/email-templates.php

# Issues Fixed:
1. Validation done on field marked with *
2. Page updates all values to meta table
3. Toster notification shown after click on save setting
4. Loader Works properly and refreshes the page after the update.
5. All the feilds are sanitized properly. 

Note: All reported issues are fixed. So this issue is marked as closed. Shiffi is not present in the office so this ticket is closed by Sandeep.

Changed by:
Shiffi, Sandeep
