### ISSUE TITLE
Text Email tab of Email Management Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#16]
Hi Sonali,

Here are the tasks for you for the Test Email tab of Email Management Page/Screen.

• By clicking on Test Email tab the following steps should be done-
• Validate the fields marked with star(*).
• Make changes in main file,footer file and action-library file for sending test email.
• By clicking on Send Test Email  button,all other fields should be hidden and a text area should be shown with a message "Your Email has been sent Successfully".

Regards
Sonal
Team Leader

**Comment by tech-prodigy10** [comment]
Issue ID: #16 Changes Made at  9:15 AM

Changed Files: 
1. captcha-master.php
2. lib\action-library.php
3. includes\footer.php
4. email-management\email-management.php

Issues Fixed:
1. Created a function named as test_email
2. Created Hook
3. In constants, global $phpmailer;
4. Created case "test_email_management_module" in action-library.php
5. Created case "cpm_email_management" in footer.php
6. stripslashes in action-library.php
7. Layout changed of email-management.php

Changed By :
Sonali Sharma

Tested By:
Sonal

Note: Reported issues are fixed. So this issue is marked as closed.
