### ISSUE TITLE
Plugin Settings  of General Settings  Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/captcha-master#2]
Hi Shifi

Here are the tasks for you for the  Plugin Settings  of General Settings  Page/Screen.

• Please make sure that the page properly reads all the default settings from the meta table and displays on the  screen in respective columns.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and   needed.

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy5** [comment]
# Changed Files: 
1. includes\footer.php
2. lib\action-library
3. views\subscription\heading-setting\heading-setting.php

# Issues Fixed:
1. Page read all the default data from the database.
   2.All the checkboxes work properly.
2. Page updates all values to meta table
3. Toster notification shown after click on save setting
4. Loader Works properly and refreshes the page after the update.
5. All the feilds are sanitized properly

Note: Reported issues are fixed. So this issue is marked as closed

Changed by:

Shiffi
