### ISSUE TITLE
Sidebar Menus of Captcha Master

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#22]
Hi Ajay,

Here are the tasks for you for Sidebar Menus of Captcha Master.

• Please make sure that the all the main menus of includes/sidebar.php will be shown in lib/sidebar-menus.php.
• After that,on sidebar menus.php file make a query to fetch all the data of plugin settings.php file from  database on sidebar-menus.php.
• If Administrator is selected,then all the menus will be shown on sidebar of wordpress.
• But if any other is selected,no menu will be shown on sidebar of wordpress.

Regards
Sonal
Team Leader

**Comment by tech-prodigy3** [comment]
Issue ID: #22 Changes made at 06:06

Changed Files:

```
1. lib/admin-bar-menu.php
2. lib/sidebar-menu.php
3. views/general-setting/plugin-setting.php
```

Issues Fixed:
1. the all the main menus of includes/sidebar.php will be shown in lib/sidebar-menus.php.
   1. on sidebar menus.php file make a query to fetch all the data of plugin settings.php file from database on sidebar-menus.php.
   2. If Administrator is selected,then all the menus will be shown on sidebar of wordpress.
   3. But if any other is selected, menu will be shown to selected user on sidebar of wordpress.
   4. admin bar will shown according to the enable and disable setting of plugin settings.php 

Note: Reported issues are fixed.So this issue is marked as closed.

Changed By:
Ajay Singh
