### ISSUE TITLE
Alert Setup and Email Templates Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#27]
Hi Ajay,

Here are the tasks for you for Alert Setup and Email Templates Page/Screen.

If an "Email When a user Success Login " field of Alert Setup page is enabled, it should work like below process:
 While successfully logins the plugin , it should send the full email format/structure from Email Template page according to "Template for User Success" option.

If an "Email When a user Failed Login " field of Alert Setup page is enabled, it should work like below process:
 if login fails, it should send the full email format/structure from Email Template page according to "Template for User Failure" option.

Regards
Sonal
Team Leader

**Comment by tech-prodigy3** [comment]
Issue ID: #27 Changes made at 02:52 PM

Changed Files:
1. captcha-master.php

Issues Fixed:
1. if user log in successfully and the option " Email When a user Success Login " is enabled in  alert  setup then an email is send to admin email along with message , body ,header(cc,bcc) according to the corresponding email template for user success.
2.    if user fails to log in and the option " Email When a user failure Login " is enabled in  alert  setup then an email is send to admin email along with message , body ,header(cc,bcc) according to the corresponding email template for user failure.

Note: Reported issues are fixed.So this issue is marked as closed.

Changed By:
Ajay Singh
