### ISSUE TITLE
Manage IP Range Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#28]
Hi Ajay

Here are the tasks for you for Manage IP Range Page/Screen.

• Please make "Start Date" and "End Date" fields using date picker in "View Blocked IP Addresses    Range".
• Data should show according to blocked date range in "View Blocked IP Addresses Range " block.
• Use filters for start date and end date.
Regards
Sonal
Team Leader

**Comment by tech-prodigy3** [comment]
Issue ID: #28 Changes made at 05:58 PM

Changed Files:

```
1. includes/footer.php
2. lib/action-library.php
3. views/advance-security/manage-ip-ranges.php
```

Issues Fixed:

 1."Start Date" and "End Date" fields using date picker in "View Blocked IP Addresses Range".
 2 Data show according to blocked date range in "View Blocked IP Addresses Range " block.
 3  filters Used for start date and end date.

Note: Reported issues are fixed.So this issue is marked as closed.

Changed by:

Ajay singh
